%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [f,Fx,Fu] = ProcessModel( x, u )
    f = [ x(1) + u(1)*cos( x(3)+u(2) );...
          x(2) + u(1)*sin( x(3)+u(2) );...
          x(3) + u(2) ];
    if nargout >= 2
        Fx = [ 1 0 -u(1)*sin( x(3)+u(2) );...
               0 1  u(1)*cos( x(3)+u(2) );...
               0 0  1 ];
    end
    if nargout == 3
        Fu = [ cos( x(3)+u(2) )  -sin( x(3)+u(2) ) ;...
               sin( x(3)+u(2) )   cos( x(3)+u(2) ) ;...
                              0                  1];
    end